name: automatic-version-bump
description: Automatically bump your pom.xml version following semver rules
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: arrow-up-circle
  color: red
